### ISSUE TITLE
vector<array<3>> in scalar function interface

### ISSUE THREAD

**Issue by jjcasmar** [patr-schm/TinyAD#11]
I am trying to use the scalar_function interface to assemble my global problem, but I am finding some troubles. My mesh is defined in terms of an Eigen::Matrix<float, Eigen::Dynamic, 3> for points, and std::vector<std::array<int, 3>> for faces. However, when i do

```
 auto func = TinyAD::scalar_function<3>(faces, [](auto &element) { return 0; });
```

I get a compilation error

```
[build] /workspace/src/Velo/Physics/StVK.cpp:39:17: error: no matching function for call to 'scalar_function'
[build]    39 |     auto func = TinyAD::scalar_function<3>(faces, [](auto &element) { return 0; });
[build]       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /workspace/build/dev-release/_deps/tinyad-src/include/TinyAD/Detail/ScalarFunctionImpl.hh:302:6: note: candidate function template not viable: no known conversion from '(lambda at /workspace/src/Velo/Physics/StVK.cpp:39:51)' to 'const EvalSettings' for 2nd argument
[build]   302 | auto scalar_function(
[build]       |      ^
[build]   303 |         const VariableRangeT& _variable_range,
[build]   304 |         const EvalSettings& _settings)
[build]       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] 1 error generated.
```

I am not sure how I should use the assembling interface

**Comment by patr-schm** [comment]
Hi, in that case it should be `TinyAD::scalar_function<3>(TinyAD::range(faces.size(), ...)` (see [here](https://github.com/patr-schm/TinyAD-Examples/blob/9e95506e2364615571c9298a530034de87377f08/apps/parametrization_libigl.cc#L52)).

Hope that fixes it!
