### ISSUE TITLE
How to terminate gracefully?

### ISSUE THREAD

**Issue by zoharl3** [patr-schm/TinyAD#12]
Exceptions shouldn't be thrown out of an omp region, and they aren't caught.

For example, in ScalarObjectiveTerm::eval_with_derivatives_add(), an exception is thrown within an omp parallel:

TINYAD_ASSERT_FINITE_MAT(element_results[i_element].grad)

If an app runs on a dataset and one model is bad, then the application would terminate unexpectedly.

**Comment by patr-schm** [comment]
Hi Zohar,

fair point. In the branch [fix-parallel-exception](https://github.com/patr-schm/TinyAD/tree/fix-parallel-exception), they are now caught and re-thrown in the main thread.

I'm leaving this in a branch for the moment, because I haven't done any integration testing yet.

**Comment by zoharl3** [comment]
Looks good. I'll try it, thanks.
